# Generated by Django 4.2.4 on 2023-09-07 11:19

from django.db import migrations, models
import resume.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', storage=resume.custom_storages.DocumentStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', storage=resume.custom_storages.ImageSettingStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
